config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/categories/admin', as: 'rails_admin'
  root :to => 'categories#index'
  resources :categories do
    resources :posts
  end

  resources :posts do 
    resources :comments
  end
  get 'crawl' => 'categories#crawl'
  get '/apis/:id', to: 'categories#generate_json', as: 'apis'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category

	has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:cat_id, :point, :title, :image_url)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  Category ID:<br /> 
    <%= f.number_field :cat_id %>
  </div>
  <div class="field">
  Point:<br />
    <%= f.number_field :point %>
  </div>
  <div class="field">
  Title:<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
  Image URL:<br />
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_content.html.erb
<div class="blog-masthead">
   <div class="container">
     <nav class="blog-nav">
     <% if category_id==0 %>
       <%= link_to 'Home', categories_path, html_options = { :class=>"blog-nav-item active"} %>
      <% else %>
        <%= link_to 'Home', categories_path, html_options = { :class=>"blog-nav-item"} %>
      <% end %>

      <% categories_list.each do |category| %>
        <% if category.id == category_id %>
          <%= link_to category.name, category, html_options = { :class=>"blog-nav-item active"} %>
        <% else %>
          <%= link_to category.name, category, html_options = { :class=>"blog-nav-item"} %>
        <% end %>
      <% end %>
      
      <% if category_id==0 %>
        <%= link_to "Admin", "categories/admin", html_options = { :class=>"blog-nav-item"} %>
       <% else %>
        <%= link_to "Admin", "admin", html_options = { :class=>"blog-nav-item"} %>
       <% end %>

       <%= link_to "Crawl", crawl_path, html_options = { :class=>"blog-nav-item"} %>
       <div class="btn-group">
         <a class="btn dropdown-toggle blog-nav-item" data-toggle="dropdown" href="#">APIs <span class="caret"></span></a>
         <ul class="dropdown-menu">
           <% categories_list.each do |category| %>
             <li><%= link_to category.name, apis_path(category) %></li>
           <% end %>
         </ul>
       </div>

     </nav>
   </div>
 </div>

 <div class="container">

   <div class="blog-header">
     <h1 class="blog-title">The 9gag Blog</h1>
     <p class="lead blog-description">Forever Alone No More!</p>
   </div>

   <div class="row">

     <div class="col-sm-8 blog-main">
         <div class="blog-post">
           <h2 class="blog-post-title">
            <%= link_to post.title, post %>
           </h2> 
           <p class="blog-post-meta"><%= post.created_at %></p>
           <p class="blog-post-meta"> <%= post.point %> points</p>
           <p class="blog-post-meta"><%= post.comments.size %> comments</p>

           <p><%= image_tag(post.img_url, :alt => "#", :size => "380x330") %></p>
         </div><!-- /.blog-post -->

         <h2>Comments</h2>
         <div class="row marketing">
         <div class="col-lg-6">
          <% @post.comments.each do |comment| %>
           <%= div_for comment do %>
            <h4><%= comment.name %></h4>
            <p><%= comment.body %></p>
            <p>Posted <%= time_ago_in_words(comment.created_at) %></p>
           <% end %>
          <% end %>
          </div>
         </div>


     </div><!-- /.blog-main -->

     <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
       <div class="sidebar-module sidebar-module-inset">
         <h4>About</h4>
         <p>9GAG, Inc., is a social media website whereby users upload and share user-generated images, videos, and GIFs. The website's content, generally referred to as "internet memes" or "internet jokes", is upvoted, downvoted, and commented on by users based on its popularity at a given time.</p>
       </div>
       <div class="sidebar-module">
         <h4>Archives</h4>
         <ol class="list-unstyled">
           <li><a href="#">January 2014</a></li>
           <li><a href="#">December 2013</a></li>
           <li><a href="#">November 2013</a></li>
           <li><a href="#">October 2013</a></li>
           <li><a href="#">September 2013</a></li>
           <li><a href="#">August 2013</a></li>
           <li><a href="#">July 2013</a></li>
           <li><a href="#">June 2013</a></li>
           <li><a href="#">May 2013</a></li>
           <li><a href="#">April 2013</a></li>
           <li><a href="#">March 2013</a></li>
           <li><a href="#">February 2013</a></li>
         </ol>
       </div>
       <div class="sidebar-module">

       </div>
     </div><!-- /.blog-sidebar -->

   </div><!-- /.row -->

 </div><!-- /.container -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Cat</th>
      <th>Point</th>
      <th>Title</th>
      <th>Img url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.point %></td>
        <td><%= post.title %></td>
        <td><%= post.img_url %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'post_content', post: @post, category_id: @post.category_id,categories_list: Category.all %>